apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-back
  labels:
    app: k8-back
spec:
  selector:
    matchLabels:
      app: k8-back
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8-back
    spec:
      containers:
      - image: gcr.io/kubernetes-test-77617/remnant12/kubernetes-dist-back-final
        imagePullPolicy: Always
        name: k8-back
        env:
          - name: K8_PYTHON_API_URL
            value: "http://k8-python-api"
        ports:
          - containerPort: 8080
