apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-front
  labels:
    app: k8-front
spec:
  selector:
    matchLabels:
      app: k8-front
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8-front
    spec:
      containers:
        - image: gcr.io/kubernetes-test-77617/remnant12/kubernetes-dist-front-final-2:v2
          imagePullPolicy: Always
          name: k8-front
          ports:
            - containerPort: 80
