apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-python-api
  labels:
    app: k8-python-api
spec:
  selector:
     matchLabels:
       app: k8-python-api
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8-python-api
    spec:
      containers:
        - image: gcr.io/kubernetes-test-77617/remnant12/kubernetes-dist-api-bench-final
          imagePullPolicy: Always
          name: k8-python-api
          ports:
            - containerPort: 5000
